apiVersion: v1
kind: Service
metadata:
  name: live-streaming-demo
spec:
  selector:
    app: live-streaming-demo
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: live-streaming-demo
  labels:
    app: live-streaming-demo
spec:
  selector:
    matchLabels:
      app: live-streaming-demo
      tier: backend
  template:
    metadata:
      labels:
        app: live-streaming-demo
        tier: backend
    spec:
      containers:
        - name: dash-encoder
          image: mattiacattarinussi/live-streaming-demo-encoder
          volumeMounts:
          - mountPath: /stream
            name: stream-chunks
        - name: app-backend
          image: mattiacattarinussi/live-streaming-demo-backend
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /stream
              name: stream-chunks
      volumes:
        - name: stream-chunks
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: live-streaming-demo-frontend
spec:
  selector:
    app: live-streaming-demo
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: live-streaming-demo-frontend
  labels:
    app: live-streaming-demo
spec:
  selector:
    matchLabels:
      app: live-streaming-demo
      tier: frontend
  template:
    metadata:
      labels:
        app: live-streaming-demo
        tier: frontend
    spec:
      containers:
        - name: app-frontend
          image: mattiacattarinussi/live-streaming-demo-frontend
          ports:
            - containerPort: 80
