apiVersion: v1
kind: Service
metadata:
  name: live-streaming-demo-backend
spec:
  selector:
    app: live-streaming-demo
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: live-streaming-demo-backend
  labels:
    app: live-streaming-demo
spec:
  selector:
    matchLabels:
      app: live-streaming-demo
      tier: backend
  template:
    metadata:
      labels:
        app: live-streaming-demo
        tier: backend
    spec:
      containers:
        - name: dash-encoder
          image: mattiacattarinussi/live-streaming-demo-encoder
          volumeMounts:
          - mountPath: /chunks
            name: video-chunks
        - name: node-app
          image: mattiacattarinussi/live-streaming-demo-app
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /chunks
              name: video-chunks
      volumes:
        - name: video-chunks
          emptyDir: {}
